version: '3.4'

services:
  php:
    build: ./php
    container_name: php74-fpm
    restart: always
    volumes:
      - ./www:/var/www/html
      - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
      - ./logs/php-fpm:/var/log/php-fpm:rw
    networks:
      - prod
    expose:
      - 9000

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx-mainline
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/extend.d:/etc/nginx/extend.d:ro
      - ./logs/nginx:/var/log/nginx
    volumes_from:
      - php
    networks:
      - prod
    ports:
      - 80:80

networks:
  prod:
    name: wlan10p      
